### ISSUE TITLE
Require secure version of request

### ISSUE THREAD

**Issue by ksb86** [iaincollins/tabletojson#20]
request@2.67.0 has a security vulnerability that was fixed in 2.68.0
https://nodesecurity.io/advisories/309

I tried manually updating the dependency to 2.68.0 in package.json in node_modules and didn't see any immediate issues..

**Comment by Nordes** [comment]
It's been fixed in the commit b72e11d. So normally you can close this issue ;). (Just saying)

**Comment by iaincollins** [comment]
Ty for the poke.

I promise will do an update soon (will close that when have rolled out an update to npm).

**Comment by maugenst** [comment]
Any updates on the used request version? 

request itself is already on 2.8x.something ... Any objections to directly jump to latest version?

**Comment by iaincollins** [comment]
It's now on 2.85.0 thanks to @maugenst 🎉
