### ISSUE TITLE
CSSselect and CSSwhat deprecation warnings

### ISSUE THREAD

**Issue by mrkev** [iaincollins/tabletojson#4]
Thought I'd document this here. When installing, the following warnings are displayed: 

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

I checked `css-select`, and the earliest version available is `1.0.0`. Not sure if it's incompatible at all, but I'd suggest checking and maybe updating :hammer:

**Comment by t3chguy** [comment]
This is an issue caused by this module referencing an old version of `cheerio`, which in turn references the deprecated versions of the CSS* modules.

**Comment by iaincollins** [comment]
Thanks, sorry missed this when you logged in in July @mrkev - will resolve next week.

**Comment by mrkev** [comment]
sounds good :+1:
