### ISSUE TITLE
HTML in cells

### ISSUE THREAD

**Issue by t3chguy** [iaincollins/tabletojson#6]
maybe add a config (init parameter?) to enable/disable stripping HTML from cells. (Current behaviour uses `.text()` which strips HTML) with the flag enabled, use `.html()` instead. Only for cells, for headers using `.html()` would not be a good idea. I sometimes have to parse tables with input boxes for example.

**Comment by iaincollins** [comment]
Makes sense, it could do with some options; will take a look at that in a bit! Thanks for feedback.

**Comment by iaincollins** [comment]
I forgot all about this until I saw a bug report today, shall take a look at it on Monday.

**Comment by iaincollins** [comment]
There is now an options parameter which should make adding this easy.

**Comment by iaincollins** [comment]
Thanks, this is now documented live in version 0.6.0! Thanks for tidying up the options too :-)

**Comment by t3chguy** [comment]
:)
